###############################################################################  
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software Foundation,
#   Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
#
###############################################################################

version: '2.4'
services:

    adn-server:
        container_name: adn-server
        cpu_shares: 1024
        mem_reservation: 600m
         # Before enabling local mapping, download the file to the host machine: 
         # docker cp adn-server:/opt/ADN-DMR-Peer-Server/config/adn.cfg .
        volumes:
            - './adn.cfg:/opt/ADN-DMR-Peer-Server/config/adn.cfg:ro'
         # Change the below to inlude ports used for your OBP(s)
        ports:
            - '62031:62031/udp'
#            - '62041:62041/udp'
        # For x86_64 host devices use tag :latest , and for Raspberry arm64 / arch64 devices use tag :rpi
        image: 'registry.gitlab.com/hp3icc/fdmr/adn-server-single:latest'
        restart: "unless-stopped"
        logging:
          driver: none
        networks:
          - bridge

    adn-dashboard:
        container_name: adn-dashboard
        cpu_shares: 512
         # Before enabling local mapping, download the file to the host machine: 
         # docker cp monitor:/opt/FDMR-Monitor/fdmr-mon.cfg .
        volumes:
             - './fdmr-mon.cfg:/opt/FDMR-Monitor/fdmr-mon.cfg:ro'
#             - './logo.png:/var/www/html/img/logo.png:ro'
#             - './bk.jpg:/var/www/html/img/bk.jpg:ro'
#             - './favicon.ico:/var/www/html/img/favicon.ico:ro'
        ports:
            - '80:80/tcp'
           # - '443:443/tcp'
            - '9000:9000'
        # For x86_64 host devices use tag :latest , and for Raspberry arm64 / arch64 devices use tag :rpi
        image: 'registry.gitlab.com/hp3icc/fdmr/adn-mon2-single:latest'
        restart: "unless-stopped"
          #Set USE_SSL = to True to enable TLS support
          #you'll need to actually generate the certtificates too
          #using these commands when the container is running:

          #docker exec -it adn-dashboard gencert.sh <admin email> <server FQDN>
          #docker-compose restart adn-dashboard

          #This only needs to be done once - unless the files in the volumes above are deleted.

          #The container will handle renewing the certificates every 60 days.  

          #Note -the gencert.sh script only works when the webserver is available on the default port 80  
          #If it's on non-standard ports, you'll need to request the certificates manually. 
        logging:
          driver: none
        networks:
          - bridge

networks:
  bridge:
    driver: bridge

