###############################################################################  
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software Foundation,
#   Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
#
###############################################################################

version: '2.4'
services:

    adn-server:
        container_name: adn-server
        cpu_shares: 1024
        mem_reservation: 600m
         # Before enabling local mapping, download the file to the host machine: 
         # docker cp adn-server:/opt/ADN-DMR-Peer-Server/config/adn.cfg .
        volumes:
            - './adn.cfg:/opt/ADN-DMR-Peer-Server/config/adn.cfg:ro'
         # Change the below to inlude ports used for your OBP(s)
#        ports:
#            - '62041:62041/udp'
        # For x86_64 host devices use tag :latest , and for Raspberry arm64 / arch64 devices use tag :rpi
        image: 'registry.gitlab.com/hp3icc/fdmr/adn-server-self-service:latest'
        restart: "unless-stopped"
        logging:
          driver: none
        networks:
          - bridge

    mariadb:
        image: 'lscr.io/linuxserver/mariadb:latest'
        container_name: mariadb
        restart: "always"
        volumes:
            - './mysql:/config'
        environment:
            - MYSQL_ROOT_PASSWORD=hbmon
        logging:
          driver: none
        networks:
          - bridge

    monitor:
        container_name: monitor
        cpu_shares: 512
         # Before enabling local mapping, download the file to the host machine: 
         # DASHBOARD Style:   1 for OA4DOA , dash 2 for CS8ABG
         # file config dash 1 :     docker cp monitor:/opt/FDMR-Monitor1/fdmr-mon.cfg .
         # file config dash 2 :     docker cp monitor:/opt/FDMR-Monitor2/fdmr-mon.cfg .
        volumes:
            - './fdmr-mon.cfg:/opt/FDMR-Monitor2/fdmr-mon.cfg:ro'
#            - './logo.png:/opt/FDMR-Monitor2/html/img/logo.png:ro'
#            - './bk.jpg:/opt/FDMR-Monitor2/html/img/bk.jpg:ro'
#            - './favicon.ico:/opt/FDMR-Monitor2/html/img/favicon.ico:ro'
        ports:
            - '80:80/tcp'
            - '443:443/tcp'
            - '9000:9000'
            - '62031:62031/udp'
        depends_on:
            - 'adn-server'
            - 'mariadb'
        environment:
            - MYSQLUSER=root
            - MYSQLPASS=hbmon
          # For info TZ list:   https://gist.github.com/alejzeis/ad5827eb14b5c22109ba652a1a267af5#file-timezone-mappings-csv
            - TZ=America/Panama
          # Select DASHBOARD Style:   1 to OA4DOA , dash 2 to CS8ABG
            - DASHBOARD=2
          # To enable SSL, enter the dashboard's DNS and your email account.
            - USE_SSL=False
            - DNS_URL=
            - EMAIL=
        # For x86_64 host devices use tag :latest , and for Raspberry arm64 / arch64 devices use tag :rpi
        image: 'registry.gitlab.com/hp3icc/fdmr/adn-mon2-selfservice:latest'
        restart: "always"
        logging:
          driver: none
        networks:
          - bridge

    autoheal:
        image: willfarrell/autoheal:latest
        tty: true
        container_name: autoheal
        restart: always
        environment:
            - AUTOHEAL_CONTAINER_LABEL=all
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

networks:
  bridge:
    driver: bridge

